sudo: false

language: go

matrix:
  include:
    - go: 1.4

install:
  - go get github.com/tools/godep
  - ./hack/install-etcd.sh
  - ./hack/build-go.sh
  - export PATH=$GOPATH/bin:./third_party/etcd:$PATH

script:
  - make verify BRANCH=$TRAVIS_BRANCH

notifications:
  slack: hyperteam:spb3r9ctER5jIpm9thD5pWNo
